### ISSUE TITLE
//bin/bash: line 1: color: command not found

### ISSUE THREAD

**Issue by yousaf465** [remz1337/ProxmoxVE#2]
### ✅ Have you read and understood the above guidelines?

yes

### 📜 What is the name of the script you are using?

Frigate

### 📂 What was the exact command used to execute the script?

bash -c "$(wget -qLO - https://github.com/remz1337/Proxmox/raw/remz/ct/frigate.sh)"

### 📝 Provide a clear and concise description of the issue.

 ✓ Rebooted LXC
 //bin/bash: line 1: color: command not found
 |^C@proxmox:~# 

running the script result in this error. 

### ⚙️ What settings are you using?

- [X] Default Settings
- [ ] Advanced Settings

### 🖥️ Which Linux distribution are you using?

Debian 11

### 🔄 Steps to reproduce the issue.

run frigate script. 

### ❌ Paste the full error output (if available).

 ✓ Rebooted LXC
 //bin/bash: line 1: color: command not found
 |^C@proxmox:~#

**Comment by remz1337** [comment]
Not sure if it's a copy/paste error, but your issue still mentions the old repo. Please run the script using the new repo (notice the change from `Proxmox` to `ProxmoxVE`):
`bash -c "$(wget -qLO - https://github.com/remz1337/ProxmoxVE/raw/remz/ct/frigate.sh)"`

**Comment by yousaf465** [comment]
![image](https://github.com/user-attachments/assets/b7074cb9-8664-4081-bd38-576bf0f82455)
![image](https://github.com/user-attachments/assets/547d1da7-50c4-435f-937e-a4a9219c7be9)
same issue

**Comment by remz1337** [comment]
Weird, works fine on my end:
```
    ______     _             __     
   / ____/____(_)___ _____ _/ /____ 
  / /_  / ___/ / __ `/ __ `/ __/ _ \
 / __/ / /  / / /_/ / /_/ / /_/  __/
/_/   /_/  /_/\__, /\__,_/\__/\___/ 
             /____/                 
  ⚙️  Using Default Settings
  🖥️  Operating System: debian
  🌟  Version: 11
  📦  Container Type: Unprivileged
  💾  Disk Size: 40GB
  🧠  CPU Cores: 4
  🛠️  RAM Size: 4096MB
  🆔  Container ID: 120
Add common sudo user with SSH access: no
Enable Shared Mount: no
Configure Postfix Satellite: no
Passthrough Nvidia GPU: yes
  🚀  Creating a Frigate LXC using the above default settings
  
  ✔️  Using local for Template Storage.
  ✔️  Using local-lvm for Container Storage.
  ✔️  Updated LXC Template List
  ✔️  LXC Container 120 was successfully created.
  ✔️  Started LXC Container
Customizing LXC creation
  ✔️  Rebooted LXC
  ✔️  Set up Container OS
  ✔️  Network Connected: 192.168.1.239 
  ✔️  IPv4 Internet Connected
  ✖️  IPv6 Internet Not Connected
  ✔️  DNS Resolved github.com to 140.82.112.3
...
```
I think it's due to slow network startup in the LXC after rebooting. If the network isn't available, the script is unable to download the `install.func` file and thus, doesn't know about the `color` function.

I've increased the timer from 1 to 5. Can you try again?

**Comment by rubencm** [comment]
> Not sure if it's a copy/paste error, but your issue still mentions the old repo. Please run the script using the new repo (notice the change from `Proxmox` to `ProxmoxVE`): `bash -c "$(wget -qLO - https://github.com/remz1337/ProxmoxVE/raw/remz/ct/frigate.sh)"`

I had this problem too, the readme of this repo use commands that point to the old repo

**Comment by remz1337** [comment]
Good catch, thanks for pointing it out. I have fixed it. Can you confirm the using the new repo fixes this issue?

**Comment by rubencm** [comment]
> Good catch, thanks for pointing it out. I have fixed it. Can you confirm the using the new repo fixes this issue?

No, it dont, i created an issue for it

**Comment by remz1337** [comment]
Looks like your are facing a different issue in https://github.com/remz1337/ProxmoxVE/issues/3, so I'm closing this one
